version: '3.8'

services:
  dicom-receiver:
    build: .
    platform: linux/amd64
    ports:
      - "${DICOM_RECEIVER_PORT:-11112}:${DICOM_RECEIVER_PORT:-11112}"
    volumes:
      - ./data/storage:/data/storage
      - ./data/zips:/data/zips
      - ./data/logs:/data/logs
    environment:
      - DICOM_RECEIVER_PORT=${DICOM_RECEIVER_PORT}
      - DICOM_RECEIVER_AE_TITLE=${DICOM_RECEIVER_AE_TITLE}
      - DICOM_RECEIVER_STORAGE_DIR=${DICOM_RECEIVER_STORAGE_DIR}
      - DICOM_RECEIVER_TIMEOUT=${DICOM_RECEIVER_TIMEOUT}
      - DICOM_RECEIVER_LOG_LEVEL=${DICOM_RECEIVER_LOG_LEVEL}
      - DICOM_RECEIVER_LOG_FILE=${DICOM_RECEIVER_LOG_FILE}
      - DICOM_RECEIVER_API_URL=${DICOM_RECEIVER_API_URL}
      - DICOM_RECEIVER_API_USERNAME=${DICOM_RECEIVER_API_USERNAME}
      - DICOM_RECEIVER_API_PASSWORD=${DICOM_RECEIVER_API_PASSWORD}
      # - DICOM_RECEIVER_API_TOKEN=${DICOM_RECEIVER_API_TOKEN}
      - DICOM_RECEIVER_AUTO_UPLOAD=${DICOM_RECEIVER_AUTO_UPLOAD}
      - DICOM_RECEIVER_ZIP_DIR=${DICOM_RECEIVER_ZIP_DIR}
      - DICOM_RECEIVER_CLEANUP_AFTER_UPLOAD=${DICOM_RECEIVER_CLEANUP_AFTER_UPLOAD}
      - DICOM_RECEIVER_MAX_RETRIES=${DICOM_RECEIVER_MAX_RETRIES}
      - DICOM_RECEIVER_RETRY_DELAY=${DICOM_RECEIVER_RETRY_DELAY}
      - DICOM_RECEIVER_MAP_FILENAME=${DICOM_RECEIVER_MAP_FILENAME}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s = socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.connect(('localhost', 11112)); s.close()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s